services:
  night-planner-postgres:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: $NIGHT_PLANNER_POSTGRES_USER
      POSTGRES_PASSWORD: $NIGHT_PLANNER_POSTGRES_PASSWORD
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - night-planner-postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  #telegram-web-app:
  night-planner-web-app:
    container_name: night-planner-web-app
    build:
      context: ../web-app/src/NightPlanner.Blazor
      dockerfile: NightPlanner.Blazor.Presentation/Dockerfile
    ports:
      - "3000:8080"
    environment:
      ApiPaths__ApiGateway: $NIGHT_PLANNER_WEB_APP_API_PATH

  #backend
  night-planner-api:
    container_name: night-planner-api
    build:
      context: ../backend/src
      dockerfile: API/Planner.Api/Dockerfile
    ports:
      - "5001:8080"
    environment:
      ConnectionStrings__Database: $NIGHT_PLANNER_TASK_TRACKER_DATABASE_CONNECTION

volumes:
  night-planner-postgres-data:
