services:
  night-planner-postgres:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: $NIGHT_PLANNER_POSTGRES_USER
      POSTGRES_PASSWORD: $NIGHT_PLANNER_POSTGRES_PASSWORD
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - ../2. Init Database:/docker-entrypoint-initdb.d
      - night-planner-postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  #telegram-web-app:
  night-planner-web-app:
    container_name: night-planner-web-app
    build:
      context: ../web-app/src/NightPlanner.Blazor
      dockerfile: NightPlanner.Blazor.Presentation/Dockerfile
    ports:
      - "3000:8080"
    environment:
      ApiPaths__ApiGateway: $NIGHT_PLANNER_WEB_APP_API_PATH

  #backend
  night-planner-api-gateway:
    container_name: night-planner-api-gateway
    build:
      context: ../backend/api-gateway/NightPlanner.ApiGateway
      dockerfile: NightPlanner.ApiGateway/Dockerfile
    ports:
      - "4000:8080"
    environment:
      Ocelot__Host: $NIGHT_PLANNER_API_GATEWAY_OCELOT_HOST

  night-planner-task-tracker:
    container_name: night-planner-task-tracker
    build:
      context: ../backend/microservices/task-tracker
      dockerfile: TaskTracker.Presentation/TaskTracker.Presentation.Api/Dockerfile
    ports:
      - "5001:8080"
    environment:
      ConnectionStrings__Database: $NIGHT_PLANNER_TASK_TRACKER_DATABASE_CONNECTION

volumes:
  night-planner-postgres-data:
