name: "Build & Push Planner Api"
on:
  push:
    branches: ["master"]
    paths: ["backend/src/**"]
  workflow_dispatch:
jobs:
  build:
    name: "Build & Publish Planner Api"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v3

      - name: "Set up Docker Buildx"
        uses: docker/setup-buildx-action@v2

      - name: "Login to GitHub Registry"
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.DOCKER_REGISTRY }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_TOKEN }}

      - name: "Build & Publish Planner Api Image"
        uses: docker/build-push-action@v4
        with:
          context: ./backend/src
          file: ./backend/src/API/Planner.Api/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_REGISTRY }}/night-planner-api:latest
          platforms: linux/amd64
          provenance: false

  deploy:
    name: "Deploy Planner Api"
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: "Install SSH Key"
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            sudo su

            sudo docker login ${{ secrets.DOCKER_REGISTRY }} -u ${{ secrets.REGISTRY_USERNAME }} -p ${{ secrets.REGISTRY_TOKEN }}

            sudo docker pull ${{ secrets.DOCKER_REGISTRY }}/night-planner-api:latest

            cd ./docker

            sudo docker compose -f docker-compose.yaml rm -s night-planner-api

            sudo docker compose -f docker-compose.yaml up night-planner-api -d
