name: "Build & Push Api Gateway"
on:
  push:
    branches: ["master"]
    paths: ["backend/api-gateway/NightPlanner.ApiGateway/**"]
  workflow_dispatch:
jobs:
  build:
    name: "Build & Publish Api Gateway"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v3

      - name: "Set up Docker Buildx"
        uses: docker/setup-buildx-action@v2

      - name: "Login to GitHub Registry"
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.DOCKER_REGISTRY }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_TOKEN }}

      - name: "Build & Publish Api Gateway Image"
        uses: docker/build-push-action@v4
        with:
          context: ./backend/api-gateway/NightPlanner.ApiGateway
          file: ../backend/api-gateway/NightPlanner.ApiGateway/NightPlanner.ApiGateway/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_REGISTRY }}/night-planner-api-gateway:latest
          platforms: linux/amd64
          provenance: false

  deploy:
    name: "Deploy Backend"
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: "Install SSH Key"
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            sudo su

            docker login ${{ secrets.DOCKER_REGISTRY }} -u ${{ secrets.REGISTRY_USERNAME }} -p ${{ secrets.REGISTRY_TOKEN }}

            docker pull ${{ secrets.DOCKER_REGISTRY }}/night-planner-api-gateway:latest

            docker stop night-planner-api-gateway

            docker rm night-planner-api-gateway

            cd ./docker

            docker compose -f docker-compose.yaml up night-planner-api-gateway -d --build
